package rq;

import benchmark.metrics.computers.violation.BenchmarkViolationComputer;
import benchmark.metrics.computers.violation.models.ViolationKind;
import benchmark.metrics.computers.violation.writer.CsvWriter;
import benchmark.utils.CaseInfo;
import benchmark.utils.Configuration.Configuration;
import benchmark.utils.Configuration.ConfigurationFactory;
import org.refactoringminer.astDiff.actions.ProjectASTDiff;

import static benchmark.utils.Helpers.runWhatever;

/* Created by pourya on 2023-09-19 6:18 p.m. */

/***
 * How many semantically incompatible mappings are generated by each tool?
 */
public class RQ2 implements RQ{
    private ViolationKind[] violationKinds = ViolationKind.values();

    public void setViolationKinds(ViolationKind[] violationKinds) {
        this.violationKinds = violationKinds;
    }

    private static void rq2(Configuration[] configurations, ViolationKind[] violationKindsToCheck) throws Exception {
        BenchmarkViolationComputer benchmarkViolationComputer = new BenchmarkViolationComputer(configurations, violationKindsToCheck);
        for (Configuration configuration : configurations) {
            for (CaseInfo info : configuration.getAllCases()) {
                {
                    System.out.println("Working on " + info.getRepo() + " " + info.getCommit());
                    ProjectASTDiff projectASTDiff = runWhatever(info.getRepo(), info.getCommit());
                    benchmarkViolationComputer.compute(projectASTDiff, info, configuration);
                }
            }
        }
        new CsvWriter(benchmarkViolationComputer).writeForAllTools();
    }

    @Override
    public void run(Configuration[] confs) throws Exception {
        rq2(confs, violationKinds);
    }
}



