package rq.rm3;

import benchmark.data.diffcase.IBenchmarkCase;
import benchmark.data.exp.ExperimentsEnum;
import benchmark.data.exp.IExperiment;
import benchmark.generators.tools.ASTDiffToolEnum;
import benchmark.generators.tools.models.IASTDiffTool;
import benchmark.metrics.computers.violation.BenchmarkViolationComputer;
import benchmark.metrics.computers.violation.models.ViolationKind;
import benchmark.metrics.computers.violation.writer.CsvWriter;
import rq.RQ;

import java.util.Set;

/* Created by pourya on 2023-09-19 6:18 p.m. */

/***
 * How many semantically incompatible mappings are generated by each tool?
 */
public class RQ2 implements RQ {
    private ViolationKind[] violationKinds = ViolationKind.values();

    public void setViolationKinds(ViolationKind[] violationKinds) {
        this.violationKinds = violationKinds;
    }

    private static void rq2(IExperiment[] experiments, ViolationKind[] violationKindsToCheck) throws Exception {
        BenchmarkViolationComputer benchmarkViolationComputer = new BenchmarkViolationComputer(experiments, violationKindsToCheck);
        for (IExperiment experiment : experiments) {
            for (IBenchmarkCase info : experiment.getDataset().getCases()) {
                {
                    System.out.println("Working on " + info.getRepo() + " " + info.getCommit());
                    benchmarkViolationComputer.compute(info, experiment);
                }
            }
        }
        new CsvWriter(benchmarkViolationComputer).writeForAllTools();
    }

    @Override
    public void run(IExperiment[] experiments) throws Exception {
        rq2(experiments, violationKinds);
    }

    public static void main(String[] args) throws Exception {
        IExperiment e1 = ExperimentsEnum.REF_EXP_3_0;
        IExperiment e2 = ExperimentsEnum.REF_EXP_2_1;
        Set<IASTDiffTool> tools = Set.of(
                ASTDiffToolEnum.GOD,
                ASTDiffToolEnum.RMD,
                ASTDiffToolEnum.GTG,
                ASTDiffToolEnum.GTS,
                ASTDiffToolEnum.IJM_I,
                ASTDiffToolEnum.MTD_I,
                ASTDiffToolEnum.EXT_FGT_G,
                ASTDiffToolEnum.EXT_FGT_S
        );
        e1.setTools(tools);
        e2.setTools(tools);
        new RQ2().run(
                new IExperiment[]{
                        e1,
                        e2
                }
        );
    }
}



